### ISSUE TITLE
Could someone please share a macro in XML format?

### ISSUE THREAD

**Issue by ctocopok** [komefai/PS4Macro#28] opened 2018-04-10 08:54 UTC
Greeting. This is not actually an issue.
Due to using of PS Remote play in a emulated environment (Virtual box) with win7 being a host system,any usage of wired DS4 controller crashes my system.
So I cannot record any macros with this great product.
But I still would like to test if those macros would be played and percepted by PS RP.
For that reason I would like to see any working macro in XML format so I could possibly adapt it for my needs. I am not any good in C# coding (can code a little with python/php/asm) and the limited emulated environment has no resources to install MS VS, so coding a dll is not an option for me :(
Thank you guys.
And thumbs up for good work for komefai!

**Comment by ctocopok** [comment] 2018-04-10 10:59
I have just found some other's macro for some game not important for my purposes. 
It weights 3.5Mb of pure XML code and seems to be just a log of DualShock states.
I have no problem with writing a script that would list such states in my needed order, but... how are the delays between the states encoded? eg, I send 1 state like square pressed, and how do i "release" it after needed timeelapsed?

**Comment by ctocopok** [comment] 2018-04-11 12:46
Well...
Some feedback after I spent 6 hours of tuning, "scripting" and figuring things out.
First come first - stability. There is quite a few of it. In my environment I can only control playstation while the remapper subwindow is open. Since that window is modal, I cannot control PS4Macro window while it's open and I am still unsure if that is working as intended.
Secondly, it seems that sometimes the PS Remote play loses the emulated controller, or, what is more probable, PS4 Macro somehow loses it's injects into the control flow. What I mean is that at some point of execution, RemotePlay stops responding to keyboard keypresses, all of them, including Enter/Escape keys which normally work even without PS4Macro. After closing PS4Macro my ability to send Enters and Escapes returns, but restarting PS4Macro kills the control again.
Maybe (not sure if it really is) PS RP changes it's PID, because even after closing both PS4M and RP does not help. I have to "reboot" the win10 virtual machine to regain control with PS4 Macro.
Next thing is timings... Since I play inside an emulated windows system, I cannot measure my keypresses' length. Neither can I script those without MS Visual C. That leads to a problem that two equal keypresses from keyboard lead to different actions (may it be a single step with a game's character or a long run).

What I have somehow achieved is a script for AutoIt, which sends keypresses to remoteplay, which, in turn, having remapper window open, translates those into DS4 button presses. That works sometimes, but due to stability and timings problems I cannot rely on such contruction to grind what I need in my games :)
I suppose that a further step from having a recorded XML macro to be played to having a sort of scripting language for writing Macros might be done like it is with AutoIt system. Until than my personal circumstances do not allow me to fully utilize the power of this tool.
Anyways, what I described could be acknowledged as the best result from a series of attempts with multiple tools. At least I don't need a controlled attached, which is great.
Maybe I would achieve even better results by upgrading the host system to win10, but that is not an option for me for several reasons, one of which is ability to minimize the virtual system and have a computer avaliable for different tasks while grinding in PS4 games :)
Thank you komefai for your good work.
PS. komefai.com does not respond to http requests, although it does resolve.


At some point

**Comment by komefai** [comment] 2018-04-11 13:50
Hi, thanks for the report!

> In my environment I can only control playstation while the remapper subwindow is open. Since that window is modal, I cannot control PS4Macro window while it's open and I am still unsure if that is working as intended

The Remapper window is intentionally a blocking dialog because there is nothing in the main window that has to be controlled at the moment. Allowing to control the main window will most likely cause unexpected behaviors. So the restriction is required for now.

> Secondly, it seems that sometimes the PS Remote play loses the emulated controller, or, what is more probable, PS4 Macro somehow loses it's injects into the control flow

You're correct, it's definitely PS4 Macro losing the injection somehow because the keyboard hook is still working but the injection does not (explains why normal buttons like esc doesn't work). However, I'm not sure what caused this problem. I've been running a script 24/7 for 4-5 months now and never encountered this problem. It might be related to the VM or maybe the PID as you've suggested.

> Next thing is timings... Since I play inside an emulated windows system, I cannot measure my keypresses' length. Neither can I script those without MS Visual C. That leads to a problem that two equal keypresses from keyboard lead to different actions (may it be a single step with a game's character or a long run).

It is almost impossible to achieve perfect timing from a macro file unless you have a PC powerful enough to execute tasks in perfect intervals (etc. 30fps). I find that writing a C# script improves a lot on timing accuracy because controls can be scheduled (eg. Press and hold R2 for 5 seconds) instead of spamming R2 data packets 10-15 times in a row (wasting CPU to press and hold). I hope that you can give C# scripting a try some day.

> Thank you komefai for your good work.
PS. komefai.com does not respond to http requests, although it does resolve.

You're welcome and thank you so much for letting me know about the website being down!!! :D

PS. I'm closing this issue but feel free to leave questions.

**Closed by komefai** 2018-04-11 13:50 UTC
